/* AUTO-GENERATED by hilbench.ml.codegen - do not edit. */
#ifndef MODEL_ZOO_H
#define MODEL_ZOO_H

#include "microinfer.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Buffer sizes = maximum over the models that are compiled in. */
#define MI_ZOO_ARENA_SIZE_0 4u
#if !defined(MI_EXCLUDE_CAN_IDS_MLP) && 64u > MI_ZOO_ARENA_SIZE_0
#define MI_ZOO_ARENA_SIZE_1 64u
#else
#define MI_ZOO_ARENA_SIZE_1 MI_ZOO_ARENA_SIZE_0
#endif
#if !defined(MI_EXCLUDE_SENSOR_AE) && 128u > MI_ZOO_ARENA_SIZE_1
#define MI_ZOO_ARENA_SIZE_2 128u
#else
#define MI_ZOO_ARENA_SIZE_2 MI_ZOO_ARENA_SIZE_1
#endif
#if !defined(MI_EXCLUDE_IMU_GNSS_CNN1D) && 2048u > MI_ZOO_ARENA_SIZE_2
#define MI_ZOO_ARENA_SIZE_3 2048u
#else
#define MI_ZOO_ARENA_SIZE_3 MI_ZOO_ARENA_SIZE_2
#endif
#if !defined(MI_EXCLUDE_KWS_DSCNN) && 8000u > MI_ZOO_ARENA_SIZE_3
#define MI_ZOO_ARENA_SIZE_4 8000u
#else
#define MI_ZOO_ARENA_SIZE_4 MI_ZOO_ARENA_SIZE_3
#endif
#if !defined(MI_EXCLUDE_HAR_CNN1D) && 4096u > MI_ZOO_ARENA_SIZE_4
#define MI_ZOO_ARENA_SIZE_5 4096u
#else
#define MI_ZOO_ARENA_SIZE_5 MI_ZOO_ARENA_SIZE_4
#endif
#if !defined(MI_EXCLUDE_CAN_IDS_ROAD) && 128u > MI_ZOO_ARENA_SIZE_5
#define MI_ZOO_ARENA_SIZE_6 128u
#else
#define MI_ZOO_ARENA_SIZE_6 MI_ZOO_ARENA_SIZE_5
#endif
#if !defined(MI_EXCLUDE_MIMII_FAN_AE) && 400u > MI_ZOO_ARENA_SIZE_6
#define MI_ZOO_ARENA_SIZE_7 400u
#else
#define MI_ZOO_ARENA_SIZE_7 MI_ZOO_ARENA_SIZE_6
#endif
#define MI_ZOO_ARENA_SIZE MI_ZOO_ARENA_SIZE_7

#define MI_ZOO_MAX_IN_0 4u
#if !defined(MI_EXCLUDE_CAN_IDS_MLP) && 32u > MI_ZOO_MAX_IN_0
#define MI_ZOO_MAX_IN_1 32u
#else
#define MI_ZOO_MAX_IN_1 MI_ZOO_MAX_IN_0
#endif
#if !defined(MI_EXCLUDE_SENSOR_AE) && 64u > MI_ZOO_MAX_IN_1
#define MI_ZOO_MAX_IN_2 64u
#else
#define MI_ZOO_MAX_IN_2 MI_ZOO_MAX_IN_1
#endif
#if !defined(MI_EXCLUDE_IMU_GNSS_CNN1D) && 384u > MI_ZOO_MAX_IN_2
#define MI_ZOO_MAX_IN_3 384u
#else
#define MI_ZOO_MAX_IN_3 MI_ZOO_MAX_IN_2
#endif
#if !defined(MI_EXCLUDE_KWS_DSCNN) && 490u > MI_ZOO_MAX_IN_3
#define MI_ZOO_MAX_IN_4 490u
#else
#define MI_ZOO_MAX_IN_4 MI_ZOO_MAX_IN_3
#endif
#if !defined(MI_EXCLUDE_HAR_CNN1D) && 1152u > MI_ZOO_MAX_IN_4
#define MI_ZOO_MAX_IN_5 1152u
#else
#define MI_ZOO_MAX_IN_5 MI_ZOO_MAX_IN_4
#endif
#if !defined(MI_EXCLUDE_CAN_IDS_ROAD) && 32u > MI_ZOO_MAX_IN_5
#define MI_ZOO_MAX_IN_6 32u
#else
#define MI_ZOO_MAX_IN_6 MI_ZOO_MAX_IN_5
#endif
#if !defined(MI_EXCLUDE_MIMII_FAN_AE) && 200u > MI_ZOO_MAX_IN_6
#define MI_ZOO_MAX_IN_7 200u
#else
#define MI_ZOO_MAX_IN_7 MI_ZOO_MAX_IN_6
#endif
#define MI_ZOO_MAX_IN MI_ZOO_MAX_IN_7

#define MI_ZOO_MAX_OUT_0 4u
#if !defined(MI_EXCLUDE_CAN_IDS_MLP) && 2u > MI_ZOO_MAX_OUT_0
#define MI_ZOO_MAX_OUT_1 2u
#else
#define MI_ZOO_MAX_OUT_1 MI_ZOO_MAX_OUT_0
#endif
#if !defined(MI_EXCLUDE_SENSOR_AE) && 64u > MI_ZOO_MAX_OUT_1
#define MI_ZOO_MAX_OUT_2 64u
#else
#define MI_ZOO_MAX_OUT_2 MI_ZOO_MAX_OUT_1
#endif
#if !defined(MI_EXCLUDE_IMU_GNSS_CNN1D) && 2u > MI_ZOO_MAX_OUT_2
#define MI_ZOO_MAX_OUT_3 2u
#else
#define MI_ZOO_MAX_OUT_3 MI_ZOO_MAX_OUT_2
#endif
#if !defined(MI_EXCLUDE_KWS_DSCNN) && 12u > MI_ZOO_MAX_OUT_3
#define MI_ZOO_MAX_OUT_4 12u
#else
#define MI_ZOO_MAX_OUT_4 MI_ZOO_MAX_OUT_3
#endif
#if !defined(MI_EXCLUDE_HAR_CNN1D) && 6u > MI_ZOO_MAX_OUT_4
#define MI_ZOO_MAX_OUT_5 6u
#else
#define MI_ZOO_MAX_OUT_5 MI_ZOO_MAX_OUT_4
#endif
#if !defined(MI_EXCLUDE_CAN_IDS_ROAD) && 2u > MI_ZOO_MAX_OUT_5
#define MI_ZOO_MAX_OUT_6 2u
#else
#define MI_ZOO_MAX_OUT_6 MI_ZOO_MAX_OUT_5
#endif
#if !defined(MI_EXCLUDE_MIMII_FAN_AE) && 200u > MI_ZOO_MAX_OUT_6
#define MI_ZOO_MAX_OUT_7 200u
#else
#define MI_ZOO_MAX_OUT_7 MI_ZOO_MAX_OUT_6
#endif
#define MI_ZOO_MAX_OUT MI_ZOO_MAX_OUT_7

extern const mi_model_t mi_model_can_ids_mlp;
extern const mi_model_t mi_model_sensor_ae;
extern const mi_model_t mi_model_imu_gnss_cnn1d;
extern const mi_model_t mi_model_kws_dscnn;
extern const mi_model_t mi_model_har_cnn1d;
extern const mi_model_t mi_model_can_ids_road;
extern const mi_model_t mi_model_mimii_fan_ae;

/* NULL-terminated; models can be dropped with -DMI_EXCLUDE_<NAME>. */
extern const mi_model_t *const mi_zoo[];
extern const unsigned mi_zoo_count;

#ifdef __cplusplus
}
#endif

#endif /* MODEL_ZOO_H */
