/* AUTO-GENERATED by hilbench.ml.codegen - do not edit. */
#ifndef MODEL_ZOO_H
#define MODEL_ZOO_H

#include "microinfer.h"

#ifdef __cplusplus
extern "C" {
#endif

#define MI_ZOO_ARENA_SIZE 8000u
#define MI_ZOO_MAX_IN 490u
#define MI_ZOO_MAX_OUT 64u

extern const mi_model_t mi_model_can_ids_mlp;
extern const mi_model_t mi_model_sensor_ae;
extern const mi_model_t mi_model_imu_gnss_cnn1d;
extern const mi_model_t mi_model_kws_dscnn;

/* NULL-terminated; models can be dropped with -DMI_EXCLUDE_<NAME>. */
extern const mi_model_t *const mi_zoo[];
extern const unsigned mi_zoo_count;

#ifdef __cplusplus
}
#endif

#endif /* MODEL_ZOO_H */
